public class CalculationClassWithoutConstructor {
    //Without Constructor
    public Static void area() {
        Decimal hight = 10, width = 2;
        Decimal a = hight * width;
        system.debug('Area Of Ractangle ='+ a);
    }
    
    public Static void perimeter() {
        Decimal hight = 10, width = 2;
        Decimal a = 2*(hight + width);
        system.debug('Perimeter Of Ractangle ='+ a);
    }
}